name: Test Build

on:
  push:
    branches:
      - main
      - 'test*'

concurrency:
  group: test-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    uses: ./.github/workflows/build.yml